FROM nginx:alpine

COPY index.html /usr/share/nginx/html/
COPY app.js /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/

COPY events.html /usr/share/nginx/html/
COPY events.js /usr/share/nginx/html/

COPY manageEvents.html /usr/share/nginx/html/
COPY manageEvents.js /usr/share/nginx/html/

COPY register.html /usr/share/nginx/html/
COPY register.js /usr/share/nginx/html/

EXPOSE 80
