version: "3.8"

services:
  auth:
    build: ./auth
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=secretkey
    volumes:
      - ./auth:/app

  webd:
    build: ./webd
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=secretkey
    volumes:
      - ./webd:/app

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
