version: "3.8"

services:
  auth:
    build: ./auth
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=secretkey
    volumes:
      - ./auth:/app
      - auth_node_modules:/app/node_modules

  webd:
    build: ./webd
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=secretkey
    volumes:
      - ./webd:/app
      - webd_node_modules:/app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  auth_node_modules:
  webd_node_modules:
